### ISSUE TITLE
Server Crash on Startup on Huge Modpack (Fabric 1.21.1 / 016.9)

### ISSUE THREAD

**Issue by suerion** [KekeCreations/Arts-and-Crafts#30]
Hey, i had updated to the new Version, after this, my Modpack crash, it worked right on latest version

latest.log
https://mclo.gs/e0KVSFv
```
[13:20:31 ERROR] [main]: [Main] Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'arts_and_crafts' at 'com.kekecreations.arts_and_crafts.fabric.ArtsAndCraftsFabric'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.9.jar:?]
        at knot/net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21.1-loader.0.16.9-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_7948
        at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at knot/com.kekecreations.arts_and_crafts.core.registry.ACSpriteSources.<clinit>(ACSpriteSources.java:10) ~[arts_and_crafts-fabric-1.21-1.3.0.jar:?]
        at knot/com.kekecreations.arts_and_crafts.ArtsAndCrafts.init(ArtsAndCrafts.java:18) ~[arts_and_crafts-fabric-1.21-1.3.0.jar:?]
        at knot/com.kekecreations.arts_and_crafts.fabric.ArtsAndCraftsFabric.onInitialize(ArtsAndCraftsFabric.java:45) ~[arts_and_crafts-fabric-1.21-1.3.0.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_7948
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at knot/com.kekecreations.arts_and_crafts.core.registry.ACSpriteSources.<clinit>(ACSpriteSources.java:10) ~[arts_and_crafts-fabric-1.21-1.3.0.jar:?]
        at knot/com.kekecreations.arts_and_crafts.ArtsAndCrafts.init(ArtsAndCrafts.java:18) ~[arts_and_crafts-fabric-1.21-1.3.0.jar:?]
        at knot/com.kekecreations.arts_and_crafts.fabric.ArtsAndCraftsFabric.onInitialize(ArtsAndCraftsFabric.java:45) ~[arts_and_crafts-fabric-1.21-1.3.0.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
        ... 7 more
```

**Comment by KekeCreations** [comment]
Can you send me the modpack?

**Comment by suerion** [comment]
Will do it later, i'm not on PC yet

**Comment by KekeCreations** [comment]
Fixed in V1.3.1 (version is out now!)

**Comment by suerion** [comment]
@KekeCreations had tested newest version :) thanks for the fix, work fine now, did you need the modpack for testing enviroment?
or is it okey?

**Comment by KekeCreations** [comment]
No thanks, its okay, thank you for bug reporting and enjoy the mod!
